"""Generate src/data/ledger.ts from the engine repo's committed eval artifacts.

    python3 scripts/gen_ledger.py <engine-repo> [--ref origin/main] [--as-of YYYY-MM-DD]

Reads artifacts through `git show <ref>:evals/results/...`, so the ledger is a
rendering of COMMITTED evidence only, never of a working tree.

WHICH ARTIFACTS ARE NIGHTLIES (reproduces the 2026-09-28 hand-generated ledger):
  - single-model sweeps only (len(meta.models) == 1). A comparison sweep is a
    labelled experiment whose rows carry another model's verdicts;
  - and either a sibling `.compare.md` exists (the nightly runner writes one),
    or the run predates comparisons (before 2026-09-15). Single-model
    experiment runs after that date (no compare file) are not nightlies.

VERDICT: the comparison file's first line, reduced to its verdict token. A
first line that says there is no baseline is FIRST-RUN whatever token it
leads with (2026-10-05 leads "IMPROVEMENT" and then says "this is a first run").

NOT EMITTED: the per-night veteran-fix scorer result. That axis was found
inverted against the transcripts on 2026-10-02 and is withdrawn from the site.
"""
import argparse, json, re, subprocess, sys

def git(repo, *a):
    return subprocess.run(["git", "-C", repo, *a], check=True, capture_output=True, text=True).stdout

def verdict_of(line):
    t = re.sub(r"[*`]", "", line).strip()
    if re.search(r"first[- ]run|no baseline", t, re.I) and "COULD-NOT-COMPARE" not in t:
        return "FIRST-RUN"
    for tok in ("COULD-NOT-COMPARE", "INCOMPARABLE", "FIRST-RUN", "CLEAN", "REGRESSION", "IMPROVEMENT", "NOISE"):
        if re.search(rf"(REGRESSION:\s*)?{tok}\b", t):
            return tok
    return t.split(" ")[0]

def build(repo, ref):
    names = git(repo, "ls-tree", "--name-only", ref, "evals/results/").split()
    files = set(n.split("/")[-1] for n in names)
    rows = []
    for f in sorted(files):
        m = re.fullmatch(r"(\d{8}T\d{6}Z)\.json", f)
        if not m:
            continue
        ts = m.group(1)
        meta = json.loads(git(repo, "show", f"{ref}:evals/results/{f}"))["meta"]
        if len(meta.get("models") or []) != 1:
            continue
        has_cmp = f"{ts}.compare.md" in files
        if not has_cmp and ts >= "20260915":
            continue
        verdict = None
        if has_cmp:
            first = git(repo, "show", f"{ref}:evals/results/{ts}.compare.md").splitlines()[0]
            verdict = verdict_of(first)
        mb = meta.get("measurement_body") or {}
        body = mb.get("label") or mb.get("hostname") or None
        cv = meta.get("corpus_version") or {}
        rows.append({"date": f"{ts[:4]}-{ts[4:6]}-{ts[6:8]}", "body": body,
                     "corpus": cv.get("digest") if isinstance(cv, dict) else None, "verdict": verdict})
    return rows

def streak_of(rows):
    """Newest-backwards run of CLEAN; if the newest run is not CLEAN, the most
    recent completed run of CLEAN, plus what ended it and what followed."""
    i = len(rows) - 1
    while i >= 0 and rows[i]["verdict"] != "CLEAN":
        i -= 1
    end = i
    while i >= 0 and rows[i]["verdict"] == "CLEAN":
        i -= 1
    start = i + 1
    if end < 0:
        return None
    after = rows[end + 1:]
    return {"count": end - start + 1, "from": rows[start]["date"], "to": rows[end]["date"],
            "live": not after, "endedOn": after[0]["date"] if after else None,
            "since": [{"date": r["date"], "verdict": r["verdict"]} for r in after]}

def ts_literal(o):
    return json.dumps(o).replace('"date"', 'date').replace('"body"', 'body').replace('"corpus"', 'corpus') \
        .replace('"verdict"', 'verdict')

def render(rows, streak, as_of):
    lines = [
        "/**",
        " * Nightly run ledger — GENERATED by scripts/gen_ledger.py, not typed. Do not hand-edit;",
        " * regenerate: python3 scripts/gen_ledger.py <engine-repo> --as-of <date>.",
        " * The selection rule, the verdict reduction and what is deliberately NOT",
        " * emitted are documented in the generator, so this file can be checked.",
        " *",
        " * Boundaries that must travel with the streak:",
        " *  - it counts consecutive CLEAN comparison verdicts; a non-CLEAN verdict",
        " *    is a break in the run, not necessarily a regression (the page says which);",
        " *  - nights with no artifact are skipped, so these are runs, not calendar nights.",
        " */",
        "",
        f'export const asOf = "{as_of}";',
        "",
        "export type Night = {",
        "  date: string;",
        "  body: string | null;",
        "  corpus: string | null;",
        "  /** Verdict token of the comparison file; null when no comparison exists. */",
        "  verdict: string | null;",
        "};",
        "",
        "export const nights: Night[] = [",
        *[f"  {{ date: {json.dumps(r['date'])}, body: {json.dumps(r['body'])}, corpus: {json.dumps(r['corpus'])}, verdict: {json.dumps(r['verdict'])} }}," for r in rows],
        "];",
        "",
        "/** Most recent run of consecutive CLEAN comparisons, and what followed it. */",
        f"export const streak = {json.dumps(streak, indent=2)} as const;",
        "",
        "export const latest = " + json.dumps({k: rows[-1][k] for k in ("date", "body", "verdict")}, indent=2) + ";",
        "",
    ]
    return "\n".join(lines)

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("repo"); ap.add_argument("--ref", default="origin/main")
    ap.add_argument("--as-of", required=True); ap.add_argument("--out", default="src/data/ledger.ts")
    ap.add_argument("--print-rows", action="store_true")
    a = ap.parse_args()
    rows = build(a.repo, a.ref)
    if a.print_rows:
        for r in rows: print(r)
        sys.exit(0)
    s = streak_of(rows)
    open(a.out, "w").write(render(rows, s, a.as_of))
    print(f"{len(rows)} nights; streak {s}")
