/**
 * Nightly run ledger — GENERATED by scripts/gen_ledger.py, not typed. Do not hand-edit;
 * regenerate: python3 scripts/gen_ledger.py <engine-repo> --as-of <date>.
 * The selection rule, the verdict reduction and what is deliberately NOT
 * emitted are documented in the generator, so this file can be checked.
 *
 * Boundaries that must travel with the streak:
 *  - it counts consecutive CLEAN comparison verdicts; a non-CLEAN verdict
 *    is a break in the run, not necessarily a regression (the page says which);
 *  - nights with no artifact are skipped, so these are runs, not calendar nights.
 */

export const asOf = "2026-10-05";

export type Night = {
  date: string;
  body: string | null;
  corpus: string | null;
  /** Verdict token of the comparison file; null when no comparison exists. */
  verdict: string | null;
};

export const nights: Night[] = [
  { date: "2026-09-05", body: null, corpus: null, verdict: null },
  { date: "2026-09-08", body: null, corpus: null, verdict: null },
  { date: "2026-09-12", body: null, corpus: null, verdict: null },
  { date: "2026-09-12", body: null, corpus: null, verdict: null },
  { date: "2026-09-13", body: null, corpus: null, verdict: null },
  { date: "2026-09-14", body: null, corpus: null, verdict: null },
  { date: "2026-09-15", body: null, corpus: null, verdict: "CLEAN" },
  { date: "2026-09-16", body: null, corpus: null, verdict: "CLEAN" },
  { date: "2026-09-17", body: "ad86b7d4245a", corpus: null, verdict: "COULD-NOT-COMPARE" },
  { date: "2026-09-18", body: "983ecda93b87", corpus: null, verdict: "CLEAN" },
  { date: "2026-09-19", body: "solomon-pi", corpus: null, verdict: "CLEAN" },
  { date: "2026-09-20", body: "solomon-pi", corpus: null, verdict: "CLEAN" },
  { date: "2026-09-21", body: "solomon-pi", corpus: null, verdict: "CLEAN" },
  { date: "2026-09-22", body: "solomon-pi", corpus: null, verdict: "CLEAN" },
  { date: "2026-09-24", body: "solomon-pi", corpus: "2920eabb7b3622ed", verdict: "CLEAN" },
  { date: "2026-09-25", body: "solomon-pi", corpus: "2920eabb7b3622ed", verdict: "CLEAN" },
  { date: "2026-09-26", body: "solomon-pi", corpus: "2920eabb7b3622ed", verdict: "CLEAN" },
  { date: "2026-09-27", body: "solomon-pi", corpus: "2920eabb7b3622ed", verdict: "CLEAN" },
  { date: "2026-09-28", body: "solomon-pi", corpus: "2920eabb7b3622ed", verdict: "CLEAN" },
  { date: "2026-09-29", body: "solomon-pi", corpus: "2920eabb7b3622ed", verdict: "INCOMPARABLE" },
  { date: "2026-09-30", body: "solomon-pi", corpus: "2920eabb7b3622ed", verdict: "COULD-NOT-COMPARE" },
  { date: "2026-10-02", body: "solomon-pi", corpus: "71fbccabbb4b30b7", verdict: "FIRST-RUN" },
  { date: "2026-10-03", body: "solomon-pi", corpus: "71fbccabbb4b30b7", verdict: "FIRST-RUN" },
  { date: "2026-10-04", body: "solomon-pi", corpus: "71fbccabbb4b30b7", verdict: "FIRST-RUN" },
  { date: "2026-10-05", body: "solomon-pi", corpus: "71fbccabbb4b30b7", verdict: "FIRST-RUN" },
];

/** Most recent run of consecutive CLEAN comparisons, and what followed it. */
export const streak = {
  "count": 10,
  "from": "2026-09-18",
  "to": "2026-09-28",
  "live": false,
  "endedOn": "2026-09-29",
  "since": [
    {
      "date": "2026-09-29",
      "verdict": "INCOMPARABLE"
    },
    {
      "date": "2026-09-30",
      "verdict": "COULD-NOT-COMPARE"
    },
    {
      "date": "2026-10-02",
      "verdict": "FIRST-RUN"
    },
    {
      "date": "2026-10-03",
      "verdict": "FIRST-RUN"
    },
    {
      "date": "2026-10-04",
      "verdict": "FIRST-RUN"
    },
    {
      "date": "2026-10-05",
      "verdict": "FIRST-RUN"
    }
  ]
} as const;

export const latest = {
  "date": "2026-10-05",
  "body": "solomon-pi",
  "verdict": "FIRST-RUN"
};
